/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tms_ty_TmsDownloadNative */

#ifndef _Included_com_tms_ty_TmsDownloadNative
#define _Included_com_tms_ty_TmsDownloadNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tms_ty_TmsDownloadNative
 * Method:    tmsDownload
 * Signature: (Lcom/tms/ISocketBase;Ljava/lang/String;Ljava/lang/StringBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_tms_ty_TmsDownloadNative_tmsDownload
  (JNIEnv *, jclass, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
