package com.whty.example.pojo;

import java.util.ArrayList;
import java.util.List;

public class DeviceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public DeviceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDevicesnIsNull() {
            addCriterion("deviceSN is null");
            return (Criteria) this;
        }

        public Criteria andDevicesnIsNotNull() {
            addCriterion("deviceSN is not null");
            return (Criteria) this;
        }

        public Criteria andDevicesnEqualTo(String value) {
            addCriterion("deviceSN =", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnNotEqualTo(String value) {
            addCriterion("deviceSN <>", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnGreaterThan(String value) {
            addCriterion("deviceSN >", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnGreaterThanOrEqualTo(String value) {
            addCriterion("deviceSN >=", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnLessThan(String value) {
            addCriterion("deviceSN <", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnLessThanOrEqualTo(String value) {
            addCriterion("deviceSN <=", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnLike(String value) {
            addCriterion("deviceSN like", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnNotLike(String value) {
            addCriterion("deviceSN not like", value, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnIn(List<String> values) {
            addCriterion("deviceSN in", values, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnNotIn(List<String> values) {
            addCriterion("deviceSN not in", values, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnBetween(String value1, String value2) {
            addCriterion("deviceSN between", value1, value2, "devicesn");
            return (Criteria) this;
        }

        public Criteria andDevicesnNotBetween(String value1, String value2) {
            addCriterion("deviceSN not between", value1, value2, "devicesn");
            return (Criteria) this;
        }

        public Criteria andMainkeyIsNull() {
            addCriterion("mainKey is null");
            return (Criteria) this;
        }

        public Criteria andMainkeyIsNotNull() {
            addCriterion("mainKey is not null");
            return (Criteria) this;
        }

        public Criteria andMainkeyEqualTo(String value) {
            addCriterion("mainKey =", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyNotEqualTo(String value) {
            addCriterion("mainKey <>", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyGreaterThan(String value) {
            addCriterion("mainKey >", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyGreaterThanOrEqualTo(String value) {
            addCriterion("mainKey >=", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyLessThan(String value) {
            addCriterion("mainKey <", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyLessThanOrEqualTo(String value) {
            addCriterion("mainKey <=", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyLike(String value) {
            addCriterion("mainKey like", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyNotLike(String value) {
            addCriterion("mainKey not like", value, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyIn(List<String> values) {
            addCriterion("mainKey in", values, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyNotIn(List<String> values) {
            addCriterion("mainKey not in", values, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyBetween(String value1, String value2) {
            addCriterion("mainKey between", value1, value2, "mainkey");
            return (Criteria) this;
        }

        public Criteria andMainkeyNotBetween(String value1, String value2) {
            addCriterion("mainKey not between", value1, value2, "mainkey");
            return (Criteria) this;
        }

        public Criteria andTdkIsNull() {
            addCriterion("tdk is null");
            return (Criteria) this;
        }

        public Criteria andTdkIsNotNull() {
            addCriterion("tdk is not null");
            return (Criteria) this;
        }

        public Criteria andTdkEqualTo(String value) {
            addCriterion("tdk =", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkNotEqualTo(String value) {
            addCriterion("tdk <>", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkGreaterThan(String value) {
            addCriterion("tdk >", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkGreaterThanOrEqualTo(String value) {
            addCriterion("tdk >=", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkLessThan(String value) {
            addCriterion("tdk <", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkLessThanOrEqualTo(String value) {
            addCriterion("tdk <=", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkLike(String value) {
            addCriterion("tdk like", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkNotLike(String value) {
            addCriterion("tdk not like", value, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkIn(List<String> values) {
            addCriterion("tdk in", values, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkNotIn(List<String> values) {
            addCriterion("tdk not in", values, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkBetween(String value1, String value2) {
            addCriterion("tdk between", value1, value2, "tdk");
            return (Criteria) this;
        }

        public Criteria andTdkNotBetween(String value1, String value2) {
            addCriterion("tdk not between", value1, value2, "tdk");
            return (Criteria) this;
        }

        public Criteria andPikIsNull() {
            addCriterion("pik is null");
            return (Criteria) this;
        }

        public Criteria andPikIsNotNull() {
            addCriterion("pik is not null");
            return (Criteria) this;
        }

        public Criteria andPikEqualTo(String value) {
            addCriterion("pik =", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotEqualTo(String value) {
            addCriterion("pik <>", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikGreaterThan(String value) {
            addCriterion("pik >", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikGreaterThanOrEqualTo(String value) {
            addCriterion("pik >=", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLessThan(String value) {
            addCriterion("pik <", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLessThanOrEqualTo(String value) {
            addCriterion("pik <=", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLike(String value) {
            addCriterion("pik like", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotLike(String value) {
            addCriterion("pik not like", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikIn(List<String> values) {
            addCriterion("pik in", values, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotIn(List<String> values) {
            addCriterion("pik not in", values, "pik");
            return (Criteria) this;
        }

        public Criteria andPikBetween(String value1, String value2) {
            addCriterion("pik between", value1, value2, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotBetween(String value1, String value2) {
            addCriterion("pik not between", value1, value2, "pik");
            return (Criteria) this;
        }

        public Criteria andMakIsNull() {
            addCriterion("mak is null");
            return (Criteria) this;
        }

        public Criteria andMakIsNotNull() {
            addCriterion("mak is not null");
            return (Criteria) this;
        }

        public Criteria andMakEqualTo(String value) {
            addCriterion("mak =", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotEqualTo(String value) {
            addCriterion("mak <>", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakGreaterThan(String value) {
            addCriterion("mak >", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakGreaterThanOrEqualTo(String value) {
            addCriterion("mak >=", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLessThan(String value) {
            addCriterion("mak <", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLessThanOrEqualTo(String value) {
            addCriterion("mak <=", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLike(String value) {
            addCriterion("mak like", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotLike(String value) {
            addCriterion("mak not like", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakIn(List<String> values) {
            addCriterion("mak in", values, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotIn(List<String> values) {
            addCriterion("mak not in", values, "mak");
            return (Criteria) this;
        }

        public Criteria andMakBetween(String value1, String value2) {
            addCriterion("mak between", value1, value2, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotBetween(String value1, String value2) {
            addCriterion("mak not between", value1, value2, "mak");
            return (Criteria) this;
        }

        public Criteria andTerminalnoIsNull() {
            addCriterion("terminalNo is null");
            return (Criteria) this;
        }

        public Criteria andTerminalnoIsNotNull() {
            addCriterion("terminalNo is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalnoEqualTo(String value) {
            addCriterion("terminalNo =", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoNotEqualTo(String value) {
            addCriterion("terminalNo <>", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoGreaterThan(String value) {
            addCriterion("terminalNo >", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoGreaterThanOrEqualTo(String value) {
            addCriterion("terminalNo >=", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoLessThan(String value) {
            addCriterion("terminalNo <", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoLessThanOrEqualTo(String value) {
            addCriterion("terminalNo <=", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoLike(String value) {
            addCriterion("terminalNo like", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoNotLike(String value) {
            addCriterion("terminalNo not like", value, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoIn(List<String> values) {
            addCriterion("terminalNo in", values, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoNotIn(List<String> values) {
            addCriterion("terminalNo not in", values, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoBetween(String value1, String value2) {
            addCriterion("terminalNo between", value1, value2, "terminalno");
            return (Criteria) this;
        }

        public Criteria andTerminalnoNotBetween(String value1, String value2) {
            addCriterion("terminalNo not between", value1, value2, "terminalno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoIsNull() {
            addCriterion("merchantNo is null");
            return (Criteria) this;
        }

        public Criteria andMerchantnoIsNotNull() {
            addCriterion("merchantNo is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantnoEqualTo(String value) {
            addCriterion("merchantNo =", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoNotEqualTo(String value) {
            addCriterion("merchantNo <>", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoGreaterThan(String value) {
            addCriterion("merchantNo >", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoGreaterThanOrEqualTo(String value) {
            addCriterion("merchantNo >=", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoLessThan(String value) {
            addCriterion("merchantNo <", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoLessThanOrEqualTo(String value) {
            addCriterion("merchantNo <=", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoLike(String value) {
            addCriterion("merchantNo like", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoNotLike(String value) {
            addCriterion("merchantNo not like", value, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoIn(List<String> values) {
            addCriterion("merchantNo in", values, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoNotIn(List<String> values) {
            addCriterion("merchantNo not in", values, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoBetween(String value1, String value2) {
            addCriterion("merchantNo between", value1, value2, "merchantno");
            return (Criteria) this;
        }

        public Criteria andMerchantnoNotBetween(String value1, String value2) {
            addCriterion("merchantNo not between", value1, value2, "merchantno");
            return (Criteria) this;
        }

        public Criteria andFlownoIsNull() {
            addCriterion("flowNo is null");
            return (Criteria) this;
        }

        public Criteria andFlownoIsNotNull() {
            addCriterion("flowNo is not null");
            return (Criteria) this;
        }

        public Criteria andFlownoEqualTo(String value) {
            addCriterion("flowNo =", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoNotEqualTo(String value) {
            addCriterion("flowNo <>", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoGreaterThan(String value) {
            addCriterion("flowNo >", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoGreaterThanOrEqualTo(String value) {
            addCriterion("flowNo >=", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoLessThan(String value) {
            addCriterion("flowNo <", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoLessThanOrEqualTo(String value) {
            addCriterion("flowNo <=", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoLike(String value) {
            addCriterion("flowNo like", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoNotLike(String value) {
            addCriterion("flowNo not like", value, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoIn(List<String> values) {
            addCriterion("flowNo in", values, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoNotIn(List<String> values) {
            addCriterion("flowNo not in", values, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoBetween(String value1, String value2) {
            addCriterion("flowNo between", value1, value2, "flowno");
            return (Criteria) this;
        }

        public Criteria andFlownoNotBetween(String value1, String value2) {
            addCriterion("flowNo not between", value1, value2, "flowno");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNull() {
            addCriterion("batchNo is null");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNotNull() {
            addCriterion("batchNo is not null");
            return (Criteria) this;
        }

        public Criteria andBatchnoEqualTo(String value) {
            addCriterion("batchNo =", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotEqualTo(String value) {
            addCriterion("batchNo <>", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThan(String value) {
            addCriterion("batchNo >", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThanOrEqualTo(String value) {
            addCriterion("batchNo >=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThan(String value) {
            addCriterion("batchNo <", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThanOrEqualTo(String value) {
            addCriterion("batchNo <=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLike(String value) {
            addCriterion("batchNo like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotLike(String value) {
            addCriterion("batchNo not like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoIn(List<String> values) {
            addCriterion("batchNo in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotIn(List<String> values) {
            addCriterion("batchNo not in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoBetween(String value1, String value2) {
            addCriterion("batchNo between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotBetween(String value1, String value2) {
            addCriterion("batchNo not between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagIsNull() {
            addCriterion("batchSettFlag is null");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagIsNotNull() {
            addCriterion("batchSettFlag is not null");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagEqualTo(Integer value) {
            addCriterion("batchSettFlag =", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagNotEqualTo(Integer value) {
            addCriterion("batchSettFlag <>", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagGreaterThan(Integer value) {
            addCriterion("batchSettFlag >", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("batchSettFlag >=", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagLessThan(Integer value) {
            addCriterion("batchSettFlag <", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagLessThanOrEqualTo(Integer value) {
            addCriterion("batchSettFlag <=", value, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagIn(List<Integer> values) {
            addCriterion("batchSettFlag in", values, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagNotIn(List<Integer> values) {
            addCriterion("batchSettFlag not in", values, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagBetween(Integer value1, Integer value2) {
            addCriterion("batchSettFlag between", value1, value2, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andBatchsettflagNotBetween(Integer value1, Integer value2) {
            addCriterion("batchSettFlag not between", value1, value2, "batchsettflag");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAukIsNull() {
            addCriterion("auk is null");
            return (Criteria) this;
        }

        public Criteria andAukIsNotNull() {
            addCriterion("auk is not null");
            return (Criteria) this;
        }

        public Criteria andAukEqualTo(String value) {
            addCriterion("auk =", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukNotEqualTo(String value) {
            addCriterion("auk <>", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukGreaterThan(String value) {
            addCriterion("auk >", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukGreaterThanOrEqualTo(String value) {
            addCriterion("auk >=", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukLessThan(String value) {
            addCriterion("auk <", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukLessThanOrEqualTo(String value) {
            addCriterion("auk <=", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukLike(String value) {
            addCriterion("auk like", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukNotLike(String value) {
            addCriterion("auk not like", value, "auk");
            return (Criteria) this;
        }

        public Criteria andAukIn(List<String> values) {
            addCriterion("auk in", values, "auk");
            return (Criteria) this;
        }

        public Criteria andAukNotIn(List<String> values) {
            addCriterion("auk not in", values, "auk");
            return (Criteria) this;
        }

        public Criteria andAukBetween(String value1, String value2) {
            addCriterion("auk between", value1, value2, "auk");
            return (Criteria) this;
        }

        public Criteria andAukNotBetween(String value1, String value2) {
            addCriterion("auk not between", value1, value2, "auk");
            return (Criteria) this;
        }

        public Criteria andTekIsNull() {
            addCriterion("tek is null");
            return (Criteria) this;
        }

        public Criteria andTekIsNotNull() {
            addCriterion("tek is not null");
            return (Criteria) this;
        }

        public Criteria andTekEqualTo(String value) {
            addCriterion("tek =", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekNotEqualTo(String value) {
            addCriterion("tek <>", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekGreaterThan(String value) {
            addCriterion("tek >", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekGreaterThanOrEqualTo(String value) {
            addCriterion("tek >=", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekLessThan(String value) {
            addCriterion("tek <", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekLessThanOrEqualTo(String value) {
            addCriterion("tek <=", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekLike(String value) {
            addCriterion("tek like", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekNotLike(String value) {
            addCriterion("tek not like", value, "tek");
            return (Criteria) this;
        }

        public Criteria andTekIn(List<String> values) {
            addCriterion("tek in", values, "tek");
            return (Criteria) this;
        }

        public Criteria andTekNotIn(List<String> values) {
            addCriterion("tek not in", values, "tek");
            return (Criteria) this;
        }

        public Criteria andTekBetween(String value1, String value2) {
            addCriterion("tek between", value1, value2, "tek");
            return (Criteria) this;
        }

        public Criteria andTekNotBetween(String value1, String value2) {
            addCriterion("tek not between", value1, value2, "tek");
            return (Criteria) this;
        }

        public Criteria andRandomnoIsNull() {
            addCriterion("randomNo is null");
            return (Criteria) this;
        }

        public Criteria andRandomnoIsNotNull() {
            addCriterion("randomNo is not null");
            return (Criteria) this;
        }

        public Criteria andRandomnoEqualTo(String value) {
            addCriterion("randomNo =", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoNotEqualTo(String value) {
            addCriterion("randomNo <>", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoGreaterThan(String value) {
            addCriterion("randomNo >", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoGreaterThanOrEqualTo(String value) {
            addCriterion("randomNo >=", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoLessThan(String value) {
            addCriterion("randomNo <", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoLessThanOrEqualTo(String value) {
            addCriterion("randomNo <=", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoLike(String value) {
            addCriterion("randomNo like", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoNotLike(String value) {
            addCriterion("randomNo not like", value, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoIn(List<String> values) {
            addCriterion("randomNo in", values, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoNotIn(List<String> values) {
            addCriterion("randomNo not in", values, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoBetween(String value1, String value2) {
            addCriterion("randomNo between", value1, value2, "randomno");
            return (Criteria) this;
        }

        public Criteria andRandomnoNotBetween(String value1, String value2) {
            addCriterion("randomNo not between", value1, value2, "randomno");
            return (Criteria) this;
        }

        public Criteria andDevicelocationIsNull() {
            addCriterion("deviceLocation is null");
            return (Criteria) this;
        }

        public Criteria andDevicelocationIsNotNull() {
            addCriterion("deviceLocation is not null");
            return (Criteria) this;
        }

        public Criteria andDevicelocationEqualTo(String value) {
            addCriterion("deviceLocation =", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationNotEqualTo(String value) {
            addCriterion("deviceLocation <>", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationGreaterThan(String value) {
            addCriterion("deviceLocation >", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationGreaterThanOrEqualTo(String value) {
            addCriterion("deviceLocation >=", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationLessThan(String value) {
            addCriterion("deviceLocation <", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationLessThanOrEqualTo(String value) {
            addCriterion("deviceLocation <=", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationLike(String value) {
            addCriterion("deviceLocation like", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationNotLike(String value) {
            addCriterion("deviceLocation not like", value, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationIn(List<String> values) {
            addCriterion("deviceLocation in", values, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationNotIn(List<String> values) {
            addCriterion("deviceLocation not in", values, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationBetween(String value1, String value2) {
            addCriterion("deviceLocation between", value1, value2, "devicelocation");
            return (Criteria) this;
        }

        public Criteria andDevicelocationNotBetween(String value1, String value2) {
            addCriterion("deviceLocation not between", value1, value2, "devicelocation");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_deviceinfo
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 12 15:12:08 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}