package com.whty.example.pojo;

public class DeviceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.deviceSN
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String devicesn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.mainKey
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String mainkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.tdk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String tdk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.pik
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String pik;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.mak
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String mak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.terminalNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String terminalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.merchantNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String merchantno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.flowNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String flowno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.batchNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String batchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.batchSettFlag
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private Integer batchsettflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.status
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.auk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String auk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.tek
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String tek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.randomNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String randomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_deviceinfo.deviceLocation
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    private String devicelocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.deviceSN
     *
     * @return the value of test_deviceinfo.deviceSN
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getDevicesn() {
        return devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.deviceSN
     *
     * @param devicesn the value for test_deviceinfo.deviceSN
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setDevicesn(String devicesn) {
        this.devicesn = devicesn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.mainKey
     *
     * @return the value of test_deviceinfo.mainKey
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getMainkey() {
        return mainkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.mainKey
     *
     * @param mainkey the value for test_deviceinfo.mainKey
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setMainkey(String mainkey) {
        this.mainkey = mainkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.tdk
     *
     * @return the value of test_deviceinfo.tdk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getTdk() {
        return tdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.tdk
     *
     * @param tdk the value for test_deviceinfo.tdk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setTdk(String tdk) {
        this.tdk = tdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.pik
     *
     * @return the value of test_deviceinfo.pik
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getPik() {
        return pik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.pik
     *
     * @param pik the value for test_deviceinfo.pik
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setPik(String pik) {
        this.pik = pik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.mak
     *
     * @return the value of test_deviceinfo.mak
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getMak() {
        return mak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.mak
     *
     * @param mak the value for test_deviceinfo.mak
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setMak(String mak) {
        this.mak = mak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.terminalNo
     *
     * @return the value of test_deviceinfo.terminalNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getTerminalno() {
        return terminalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.terminalNo
     *
     * @param terminalno the value for test_deviceinfo.terminalNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setTerminalno(String terminalno) {
        this.terminalno = terminalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.merchantNo
     *
     * @return the value of test_deviceinfo.merchantNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.merchantNo
     *
     * @param merchantno the value for test_deviceinfo.merchantNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.flowNo
     *
     * @return the value of test_deviceinfo.flowNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getFlowno() {
        return flowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.flowNo
     *
     * @param flowno the value for test_deviceinfo.flowNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setFlowno(String flowno) {
        this.flowno = flowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.batchNo
     *
     * @return the value of test_deviceinfo.batchNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getBatchno() {
        return batchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.batchNo
     *
     * @param batchno the value for test_deviceinfo.batchNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.batchSettFlag
     *
     * @return the value of test_deviceinfo.batchSettFlag
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public Integer getBatchsettflag() {
        return batchsettflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.batchSettFlag
     *
     * @param batchsettflag the value for test_deviceinfo.batchSettFlag
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setBatchsettflag(Integer batchsettflag) {
        this.batchsettflag = batchsettflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.status
     *
     * @return the value of test_deviceinfo.status
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.status
     *
     * @param status the value for test_deviceinfo.status
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.auk
     *
     * @return the value of test_deviceinfo.auk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getAuk() {
        return auk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.auk
     *
     * @param auk the value for test_deviceinfo.auk
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setAuk(String auk) {
        this.auk = auk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.tek
     *
     * @return the value of test_deviceinfo.tek
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getTek() {
        return tek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.tek
     *
     * @param tek the value for test_deviceinfo.tek
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setTek(String tek) {
        this.tek = tek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.randomNo
     *
     * @return the value of test_deviceinfo.randomNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getRandomno() {
        return randomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.randomNo
     *
     * @param randomno the value for test_deviceinfo.randomNo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setRandomno(String randomno) {
        this.randomno = randomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_deviceinfo.deviceLocation
     *
     * @return the value of test_deviceinfo.deviceLocation
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public String getDevicelocation() {
        return devicelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_deviceinfo.deviceLocation
     *
     * @param devicelocation the value for test_deviceinfo.deviceLocation
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    public void setDevicelocation(String devicelocation) {
        this.devicelocation = devicelocation;
    }
}