package com.whty.example.pojo;

import java.util.Date;

public class FacecompareRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.id
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.resultCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String resultcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.requestId
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String requestid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.idCardNumber
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String idcardnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.scenePicturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String scenepicturepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.picturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String picturepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.resultDetail
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String resultdetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.resultMsg
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String resultmsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.similarity
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String similarity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.appEidCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String appeidcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.dn
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private String dn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.resultTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private Date resulttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.createTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record.updateTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.id
	 * @return  the value of t_facecompare_record.id
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.id
	 * @param id  the value for t_facecompare_record.id
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.resultCode
	 * @return  the value of t_facecompare_record.resultCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getResultcode() {
		return resultcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.resultCode
	 * @param resultcode  the value for t_facecompare_record.resultCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setResultcode(String resultcode) {
		this.resultcode = resultcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.requestId
	 * @return  the value of t_facecompare_record.requestId
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getRequestid() {
		return requestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.requestId
	 * @param requestid  the value for t_facecompare_record.requestId
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setRequestid(String requestid) {
		this.requestid = requestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.idCardNumber
	 * @return  the value of t_facecompare_record.idCardNumber
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getIdcardnumber() {
		return idcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.idCardNumber
	 * @param idcardnumber  the value for t_facecompare_record.idCardNumber
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setIdcardnumber(String idcardnumber) {
		this.idcardnumber = idcardnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.scenePicturePath
	 * @return  the value of t_facecompare_record.scenePicturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getScenepicturepath() {
		return scenepicturepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.scenePicturePath
	 * @param scenepicturepath  the value for t_facecompare_record.scenePicturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setScenepicturepath(String scenepicturepath) {
		this.scenepicturepath = scenepicturepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.picturePath
	 * @return  the value of t_facecompare_record.picturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getPicturepath() {
		return picturepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.picturePath
	 * @param picturepath  the value for t_facecompare_record.picturePath
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setPicturepath(String picturepath) {
		this.picturepath = picturepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.resultDetail
	 * @return  the value of t_facecompare_record.resultDetail
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getResultdetail() {
		return resultdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.resultDetail
	 * @param resultdetail  the value for t_facecompare_record.resultDetail
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setResultdetail(String resultdetail) {
		this.resultdetail = resultdetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.resultMsg
	 * @return  the value of t_facecompare_record.resultMsg
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getResultmsg() {
		return resultmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.resultMsg
	 * @param resultmsg  the value for t_facecompare_record.resultMsg
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setResultmsg(String resultmsg) {
		this.resultmsg = resultmsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.similarity
	 * @return  the value of t_facecompare_record.similarity
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getSimilarity() {
		return similarity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.similarity
	 * @param similarity  the value for t_facecompare_record.similarity
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setSimilarity(String similarity) {
		this.similarity = similarity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.appEidCode
	 * @return  the value of t_facecompare_record.appEidCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getAppeidcode() {
		return appeidcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.appEidCode
	 * @param appeidcode  the value for t_facecompare_record.appEidCode
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setAppeidcode(String appeidcode) {
		this.appeidcode = appeidcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.dn
	 * @return  the value of t_facecompare_record.dn
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getDn() {
		return dn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.dn
	 * @param dn  the value for t_facecompare_record.dn
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setDn(String dn) {
		this.dn = dn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.resultTime
	 * @return  the value of t_facecompare_record.resultTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Date getResulttime() {
		return resulttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.resultTime
	 * @param resulttime  the value for t_facecompare_record.resultTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setResulttime(Date resulttime) {
		this.resulttime = resulttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.createTime
	 * @return  the value of t_facecompare_record.createTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.createTime
	 * @param createtime  the value for t_facecompare_record.createTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record.updateTime
	 * @return  the value of t_facecompare_record.updateTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record.updateTime
	 * @param updatetime  the value for t_facecompare_record.updateTime
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}
}