package com.whty.example.pojo;

public class FacecompareRecordAddition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record_addition.id
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record_addition.facecompareRecordId
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	private Integer facecomparerecordid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record_addition.id
	 * @return  the value of t_facecompare_record_addition.id
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record_addition.id
	 * @param id  the value for t_facecompare_record_addition.id
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record_addition.facecompareRecordId
	 * @return  the value of t_facecompare_record_addition.facecompareRecordId
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public Integer getFacecomparerecordid() {
		return facecomparerecordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record_addition.facecompareRecordId
	 * @param facecomparerecordid  the value for t_facecompare_record_addition.facecompareRecordId
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public void setFacecomparerecordid(Integer facecomparerecordid) {
		this.facecomparerecordid = facecomparerecordid;
	}
}