package com.whty.example.pojo;

public class FacecompareRecordAdditionWithBLOBs extends FacecompareRecordAddition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record_addition.picture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	private byte[] picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_facecompare_record_addition.scenePicture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	private byte[] scenepicture;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record_addition.picture
	 * @return  the value of t_facecompare_record_addition.picture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public byte[] getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record_addition.picture
	 * @param picture  the value for t_facecompare_record_addition.picture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_facecompare_record_addition.scenePicture
	 * @return  the value of t_facecompare_record_addition.scenePicture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public byte[] getScenepicture() {
		return scenepicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_facecompare_record_addition.scenePicture
	 * @param scenepicture  the value for t_facecompare_record_addition.scenePicture
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	public void setScenepicture(byte[] scenepicture) {
		this.scenepicture = scenepicture;
	}
}