package com.whty.example.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FacecompareRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public FacecompareRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andResultcodeIsNull() {
			addCriterion("resultCode is null");
			return (Criteria) this;
		}

		public Criteria andResultcodeIsNotNull() {
			addCriterion("resultCode is not null");
			return (Criteria) this;
		}

		public Criteria andResultcodeEqualTo(String value) {
			addCriterion("resultCode =", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeNotEqualTo(String value) {
			addCriterion("resultCode <>", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeGreaterThan(String value) {
			addCriterion("resultCode >", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeGreaterThanOrEqualTo(String value) {
			addCriterion("resultCode >=", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeLessThan(String value) {
			addCriterion("resultCode <", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeLessThanOrEqualTo(String value) {
			addCriterion("resultCode <=", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeLike(String value) {
			addCriterion("resultCode like", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeNotLike(String value) {
			addCriterion("resultCode not like", value, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeIn(List<String> values) {
			addCriterion("resultCode in", values, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeNotIn(List<String> values) {
			addCriterion("resultCode not in", values, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeBetween(String value1, String value2) {
			addCriterion("resultCode between", value1, value2, "resultcode");
			return (Criteria) this;
		}

		public Criteria andResultcodeNotBetween(String value1, String value2) {
			addCriterion("resultCode not between", value1, value2, "resultcode");
			return (Criteria) this;
		}

		public Criteria andRequestidIsNull() {
			addCriterion("requestId is null");
			return (Criteria) this;
		}

		public Criteria andRequestidIsNotNull() {
			addCriterion("requestId is not null");
			return (Criteria) this;
		}

		public Criteria andRequestidEqualTo(String value) {
			addCriterion("requestId =", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidNotEqualTo(String value) {
			addCriterion("requestId <>", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidGreaterThan(String value) {
			addCriterion("requestId >", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidGreaterThanOrEqualTo(String value) {
			addCriterion("requestId >=", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidLessThan(String value) {
			addCriterion("requestId <", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidLessThanOrEqualTo(String value) {
			addCriterion("requestId <=", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidLike(String value) {
			addCriterion("requestId like", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidNotLike(String value) {
			addCriterion("requestId not like", value, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidIn(List<String> values) {
			addCriterion("requestId in", values, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidNotIn(List<String> values) {
			addCriterion("requestId not in", values, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidBetween(String value1, String value2) {
			addCriterion("requestId between", value1, value2, "requestid");
			return (Criteria) this;
		}

		public Criteria andRequestidNotBetween(String value1, String value2) {
			addCriterion("requestId not between", value1, value2, "requestid");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberIsNull() {
			addCriterion("idCardNumber is null");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberIsNotNull() {
			addCriterion("idCardNumber is not null");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberEqualTo(String value) {
			addCriterion("idCardNumber =", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberNotEqualTo(String value) {
			addCriterion("idCardNumber <>", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberGreaterThan(String value) {
			addCriterion("idCardNumber >", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberGreaterThanOrEqualTo(String value) {
			addCriterion("idCardNumber >=", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberLessThan(String value) {
			addCriterion("idCardNumber <", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberLessThanOrEqualTo(String value) {
			addCriterion("idCardNumber <=", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberLike(String value) {
			addCriterion("idCardNumber like", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberNotLike(String value) {
			addCriterion("idCardNumber not like", value, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberIn(List<String> values) {
			addCriterion("idCardNumber in", values, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberNotIn(List<String> values) {
			addCriterion("idCardNumber not in", values, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberBetween(String value1, String value2) {
			addCriterion("idCardNumber between", value1, value2, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andIdcardnumberNotBetween(String value1, String value2) {
			addCriterion("idCardNumber not between", value1, value2, "idcardnumber");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathIsNull() {
			addCriterion("scenePicturePath is null");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathIsNotNull() {
			addCriterion("scenePicturePath is not null");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathEqualTo(String value) {
			addCriterion("scenePicturePath =", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathNotEqualTo(String value) {
			addCriterion("scenePicturePath <>", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathGreaterThan(String value) {
			addCriterion("scenePicturePath >", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathGreaterThanOrEqualTo(String value) {
			addCriterion("scenePicturePath >=", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathLessThan(String value) {
			addCriterion("scenePicturePath <", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathLessThanOrEqualTo(String value) {
			addCriterion("scenePicturePath <=", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathLike(String value) {
			addCriterion("scenePicturePath like", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathNotLike(String value) {
			addCriterion("scenePicturePath not like", value, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathIn(List<String> values) {
			addCriterion("scenePicturePath in", values, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathNotIn(List<String> values) {
			addCriterion("scenePicturePath not in", values, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathBetween(String value1, String value2) {
			addCriterion("scenePicturePath between", value1, value2, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andScenepicturepathNotBetween(String value1, String value2) {
			addCriterion("scenePicturePath not between", value1, value2, "scenepicturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathIsNull() {
			addCriterion("picturePath is null");
			return (Criteria) this;
		}

		public Criteria andPicturepathIsNotNull() {
			addCriterion("picturePath is not null");
			return (Criteria) this;
		}

		public Criteria andPicturepathEqualTo(String value) {
			addCriterion("picturePath =", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathNotEqualTo(String value) {
			addCriterion("picturePath <>", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathGreaterThan(String value) {
			addCriterion("picturePath >", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathGreaterThanOrEqualTo(String value) {
			addCriterion("picturePath >=", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathLessThan(String value) {
			addCriterion("picturePath <", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathLessThanOrEqualTo(String value) {
			addCriterion("picturePath <=", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathLike(String value) {
			addCriterion("picturePath like", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathNotLike(String value) {
			addCriterion("picturePath not like", value, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathIn(List<String> values) {
			addCriterion("picturePath in", values, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathNotIn(List<String> values) {
			addCriterion("picturePath not in", values, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathBetween(String value1, String value2) {
			addCriterion("picturePath between", value1, value2, "picturepath");
			return (Criteria) this;
		}

		public Criteria andPicturepathNotBetween(String value1, String value2) {
			addCriterion("picturePath not between", value1, value2, "picturepath");
			return (Criteria) this;
		}

		public Criteria andResultdetailIsNull() {
			addCriterion("resultDetail is null");
			return (Criteria) this;
		}

		public Criteria andResultdetailIsNotNull() {
			addCriterion("resultDetail is not null");
			return (Criteria) this;
		}

		public Criteria andResultdetailEqualTo(String value) {
			addCriterion("resultDetail =", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailNotEqualTo(String value) {
			addCriterion("resultDetail <>", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailGreaterThan(String value) {
			addCriterion("resultDetail >", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailGreaterThanOrEqualTo(String value) {
			addCriterion("resultDetail >=", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailLessThan(String value) {
			addCriterion("resultDetail <", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailLessThanOrEqualTo(String value) {
			addCriterion("resultDetail <=", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailLike(String value) {
			addCriterion("resultDetail like", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailNotLike(String value) {
			addCriterion("resultDetail not like", value, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailIn(List<String> values) {
			addCriterion("resultDetail in", values, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailNotIn(List<String> values) {
			addCriterion("resultDetail not in", values, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailBetween(String value1, String value2) {
			addCriterion("resultDetail between", value1, value2, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultdetailNotBetween(String value1, String value2) {
			addCriterion("resultDetail not between", value1, value2, "resultdetail");
			return (Criteria) this;
		}

		public Criteria andResultmsgIsNull() {
			addCriterion("resultMsg is null");
			return (Criteria) this;
		}

		public Criteria andResultmsgIsNotNull() {
			addCriterion("resultMsg is not null");
			return (Criteria) this;
		}

		public Criteria andResultmsgEqualTo(String value) {
			addCriterion("resultMsg =", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgNotEqualTo(String value) {
			addCriterion("resultMsg <>", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgGreaterThan(String value) {
			addCriterion("resultMsg >", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgGreaterThanOrEqualTo(String value) {
			addCriterion("resultMsg >=", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgLessThan(String value) {
			addCriterion("resultMsg <", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgLessThanOrEqualTo(String value) {
			addCriterion("resultMsg <=", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgLike(String value) {
			addCriterion("resultMsg like", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgNotLike(String value) {
			addCriterion("resultMsg not like", value, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgIn(List<String> values) {
			addCriterion("resultMsg in", values, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgNotIn(List<String> values) {
			addCriterion("resultMsg not in", values, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgBetween(String value1, String value2) {
			addCriterion("resultMsg between", value1, value2, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andResultmsgNotBetween(String value1, String value2) {
			addCriterion("resultMsg not between", value1, value2, "resultmsg");
			return (Criteria) this;
		}

		public Criteria andSimilarityIsNull() {
			addCriterion("similarity is null");
			return (Criteria) this;
		}

		public Criteria andSimilarityIsNotNull() {
			addCriterion("similarity is not null");
			return (Criteria) this;
		}

		public Criteria andSimilarityEqualTo(String value) {
			addCriterion("similarity =", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityNotEqualTo(String value) {
			addCriterion("similarity <>", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityGreaterThan(String value) {
			addCriterion("similarity >", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityGreaterThanOrEqualTo(String value) {
			addCriterion("similarity >=", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityLessThan(String value) {
			addCriterion("similarity <", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityLessThanOrEqualTo(String value) {
			addCriterion("similarity <=", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityLike(String value) {
			addCriterion("similarity like", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityNotLike(String value) {
			addCriterion("similarity not like", value, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityIn(List<String> values) {
			addCriterion("similarity in", values, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityNotIn(List<String> values) {
			addCriterion("similarity not in", values, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityBetween(String value1, String value2) {
			addCriterion("similarity between", value1, value2, "similarity");
			return (Criteria) this;
		}

		public Criteria andSimilarityNotBetween(String value1, String value2) {
			addCriterion("similarity not between", value1, value2, "similarity");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeIsNull() {
			addCriterion("appEidCode is null");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeIsNotNull() {
			addCriterion("appEidCode is not null");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeEqualTo(String value) {
			addCriterion("appEidCode =", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeNotEqualTo(String value) {
			addCriterion("appEidCode <>", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeGreaterThan(String value) {
			addCriterion("appEidCode >", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeGreaterThanOrEqualTo(String value) {
			addCriterion("appEidCode >=", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeLessThan(String value) {
			addCriterion("appEidCode <", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeLessThanOrEqualTo(String value) {
			addCriterion("appEidCode <=", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeLike(String value) {
			addCriterion("appEidCode like", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeNotLike(String value) {
			addCriterion("appEidCode not like", value, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeIn(List<String> values) {
			addCriterion("appEidCode in", values, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeNotIn(List<String> values) {
			addCriterion("appEidCode not in", values, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeBetween(String value1, String value2) {
			addCriterion("appEidCode between", value1, value2, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andAppeidcodeNotBetween(String value1, String value2) {
			addCriterion("appEidCode not between", value1, value2, "appeidcode");
			return (Criteria) this;
		}

		public Criteria andDnIsNull() {
			addCriterion("dn is null");
			return (Criteria) this;
		}

		public Criteria andDnIsNotNull() {
			addCriterion("dn is not null");
			return (Criteria) this;
		}

		public Criteria andDnEqualTo(String value) {
			addCriterion("dn =", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnNotEqualTo(String value) {
			addCriterion("dn <>", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnGreaterThan(String value) {
			addCriterion("dn >", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnGreaterThanOrEqualTo(String value) {
			addCriterion("dn >=", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnLessThan(String value) {
			addCriterion("dn <", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnLessThanOrEqualTo(String value) {
			addCriterion("dn <=", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnLike(String value) {
			addCriterion("dn like", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnNotLike(String value) {
			addCriterion("dn not like", value, "dn");
			return (Criteria) this;
		}

		public Criteria andDnIn(List<String> values) {
			addCriterion("dn in", values, "dn");
			return (Criteria) this;
		}

		public Criteria andDnNotIn(List<String> values) {
			addCriterion("dn not in", values, "dn");
			return (Criteria) this;
		}

		public Criteria andDnBetween(String value1, String value2) {
			addCriterion("dn between", value1, value2, "dn");
			return (Criteria) this;
		}

		public Criteria andDnNotBetween(String value1, String value2) {
			addCriterion("dn not between", value1, value2, "dn");
			return (Criteria) this;
		}

		public Criteria andResulttimeIsNull() {
			addCriterion("resultTime is null");
			return (Criteria) this;
		}

		public Criteria andResulttimeIsNotNull() {
			addCriterion("resultTime is not null");
			return (Criteria) this;
		}

		public Criteria andResulttimeEqualTo(Date value) {
			addCriterion("resultTime =", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeNotEqualTo(Date value) {
			addCriterion("resultTime <>", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeGreaterThan(Date value) {
			addCriterion("resultTime >", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("resultTime >=", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeLessThan(Date value) {
			addCriterion("resultTime <", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeLessThanOrEqualTo(Date value) {
			addCriterion("resultTime <=", value, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeIn(List<Date> values) {
			addCriterion("resultTime in", values, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeNotIn(List<Date> values) {
			addCriterion("resultTime not in", values, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeBetween(Date value1, Date value2) {
			addCriterion("resultTime between", value1, value2, "resulttime");
			return (Criteria) this;
		}

		public Criteria andResulttimeNotBetween(Date value1, Date value2) {
			addCriterion("resultTime not between", value1, value2, "resulttime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_facecompare_record
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 05 14:25:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}