package com.whty.example.pojo;

import java.util.Date;

public class IdCardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.id
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.name
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.sex
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.nation
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.birthDate
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.address
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.idnum
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String idnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.signingOrganization
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String signingorganization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.beginTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.endTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.picturePath
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String picturepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.inputTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private Date inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.lastQueryTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private Date lastquerytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.queryCount
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private Integer querycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_idcard.remark
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.id
     *
     * @return the value of t_idcard.id
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.id
     *
     * @param id the value for t_idcard.id
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.name
     *
     * @return the value of t_idcard.name
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.name
     *
     * @param name the value for t_idcard.name
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.sex
     *
     * @return the value of t_idcard.sex
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.sex
     *
     * @param sex the value for t_idcard.sex
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.nation
     *
     * @return the value of t_idcard.nation
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.nation
     *
     * @param nation the value for t_idcard.nation
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.birthDate
     *
     * @return the value of t_idcard.birthDate
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.birthDate
     *
     * @param birthdate the value for t_idcard.birthDate
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.address
     *
     * @return the value of t_idcard.address
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.address
     *
     * @param address the value for t_idcard.address
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.idnum
     *
     * @return the value of t_idcard.idnum
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getIdnum() {
        return idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.idnum
     *
     * @param idnum the value for t_idcard.idnum
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.signingOrganization
     *
     * @return the value of t_idcard.signingOrganization
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getSigningorganization() {
        return signingorganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.signingOrganization
     *
     * @param signingorganization the value for t_idcard.signingOrganization
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setSigningorganization(String signingorganization) {
        this.signingorganization = signingorganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.beginTime
     *
     * @return the value of t_idcard.beginTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.beginTime
     *
     * @param begintime the value for t_idcard.beginTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setBegintime(String begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.endTime
     *
     * @return the value of t_idcard.endTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.endTime
     *
     * @param endtime the value for t_idcard.endTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.picturePath
     *
     * @return the value of t_idcard.picturePath
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getPicturepath() {
        return picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.picturePath
     *
     * @param picturepath the value for t_idcard.picturePath
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.inputTime
     *
     * @return the value of t_idcard.inputTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.inputTime
     *
     * @param inputtime the value for t_idcard.inputTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.lastQueryTime
     *
     * @return the value of t_idcard.lastQueryTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public Date getLastquerytime() {
        return lastquerytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.lastQueryTime
     *
     * @param lastquerytime the value for t_idcard.lastQueryTime
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setLastquerytime(Date lastquerytime) {
        this.lastquerytime = lastquerytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.queryCount
     *
     * @return the value of t_idcard.queryCount
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public Integer getQuerycount() {
        return querycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.queryCount
     *
     * @param querycount the value for t_idcard.queryCount
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setQuerycount(Integer querycount) {
        this.querycount = querycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_idcard.remark
     *
     * @return the value of t_idcard.remark
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_idcard.remark
     *
     * @param remark the value for t_idcard.remark
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}