package com.whty.example.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ACCOUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REAL_NAME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.SEX
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.EMAIL
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.MOBILE
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ERROR_COUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private Short errorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.LAST_LOGIN_IP
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.REMARK
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATUS
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ACCOUNT
     *
     * @return the value of user.ACCOUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ACCOUNT
     *
     * @param account the value for user.ACCOUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REAL_NAME
     *
     * @return the value of user.REAL_NAME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REAL_NAME
     *
     * @param realName the value for user.REAL_NAME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.SEX
     *
     * @return the value of user.SEX
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.EMAIL
     *
     * @return the value of user.EMAIL
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.EMAIL
     *
     * @param email the value for user.EMAIL
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.MOBILE
     *
     * @return the value of user.MOBILE
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.MOBILE
     *
     * @param mobile the value for user.MOBILE
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ERROR_COUNT
     *
     * @return the value of user.ERROR_COUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public Short getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ERROR_COUNT
     *
     * @param errorCount the value for user.ERROR_COUNT
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setErrorCount(Short errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_LOGIN_TIME
     *
     * @return the value of user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for user.LAST_LOGIN_TIME
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.LAST_LOGIN_IP
     *
     * @return the value of user.LAST_LOGIN_IP
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.LAST_LOGIN_IP
     *
     * @param lastLoginIp the value for user.LAST_LOGIN_IP
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.REMARK
     *
     * @return the value of user.REMARK
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.REMARK
     *
     * @param remark the value for user.REMARK
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATUS
     *
     * @return the value of user.STATUS
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATUS
     *
     * @param status the value for user.STATUS
     *
     * @mbggenerated Thu Jun 01 13:54:06 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}