package com.whty.example.mapper;

import com.whty.example.pojo.DeviceInfo;
import com.whty.example.pojo.DeviceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int countByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int deleteByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    List<DeviceInfo> selectByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_deviceinfo
     *
     * @mbggenerated Wed Jul 12 15:12:08 CST 2017
     */
    int updateByExample(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);
}