package com.whty.example.mapper;

import com.whty.example.pojo.FacecompareRecordAddition;
import com.whty.example.pojo.FacecompareRecordAdditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.whty.example.pojo.FacecompareRecordAdditionWithBLOBs;

public interface FacecompareRecordAdditionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	long countByExample(FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int deleteByExample(FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int insert(FacecompareRecordAdditionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int insertSelective(FacecompareRecordAdditionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	List<FacecompareRecordAdditionWithBLOBs> selectByExampleWithBLOBs(FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	List<FacecompareRecordAddition> selectByExample(FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	FacecompareRecordAdditionWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") FacecompareRecordAdditionWithBLOBs record,
			@Param("example") FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") FacecompareRecordAdditionWithBLOBs record,
			@Param("example") FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByExample(@Param("record") FacecompareRecordAddition record,
			@Param("example") FacecompareRecordAdditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByPrimaryKeySelective(FacecompareRecordAdditionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(FacecompareRecordAdditionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record_addition
	 * @mbg.generated  Wed Jun 06 10:28:10 CST 2018
	 */
	int updateByPrimaryKey(FacecompareRecordAddition record);
}