package com.whty.example.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.whty.example.pojo.FacecompareRecord;
import com.whty.example.pojo.FacecompareRecordExample;

public interface FacecompareRecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	long countByExample(FacecompareRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int deleteByExample(FacecompareRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int insert(FacecompareRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int insertSelective(FacecompareRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	List<FacecompareRecord> selectByExample(FacecompareRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	FacecompareRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") FacecompareRecord record,
			@Param("example") FacecompareRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int updateByExample(@Param("record") FacecompareRecord record, @Param("example") FacecompareRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int updateByPrimaryKeySelective(FacecompareRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_facecompare_record
	 * @mbg.generated  Wed Jun 06 10:23:10 CST 2018
	 */
	int updateByPrimaryKey(FacecompareRecord record);

	int insertSelectiveWithIdBack(FacecompareRecord record);

}