package com.whty.example.mapper;

import com.whty.example.pojo.IdCardInfo;
import com.whty.example.pojo.IdCardInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdCardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int countByExample(IdCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int deleteByExample(IdCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int insert(IdCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int insertSelective(IdCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    List<IdCardInfo> selectByExample(IdCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    IdCardInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") IdCardInfo record, @Param("example") IdCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int updateByExample(@Param("record") IdCardInfo record, @Param("example") IdCardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int updateByPrimaryKeySelective(IdCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_idcard
     *
     * @mbggenerated Tue Jul 04 10:14:56 CST 2017
     */
    int updateByPrimaryKey(IdCardInfo record);
}